sudo: false
language: node_js
node_js:
  - "0.12"
  - "iojs"
  - "4.2"
  - "stable"
after_script:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
  - "cat coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js"
